version: "3.7"

services:

  shopify-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shopify-app
    restart: unless-stopped
    networks:
      - shopify-net
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker-server-config/dev/php.ini:/etc/php/7.4/fpm/php.ini
      - ./docker-server-config/dev/php.ini:/etc/php/7.4/cli/php.ini
      - ./docker-server-config/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-server-config/dev/fpm-pool.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - ./docker-server-config/dev/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf

  shopify-mysql:
    image: mariadb:10.6.4
    container_name: shopify-mysql
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - shopify-net
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shopify
      MYSQL_USER: shopify
      MYSQL_PASSWORD: shopify

volumes:
  db_data:

networks:
  shopify-net:
    driver: bridge
