version: '3'
services:
  shopify:
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile.production
    container_name: shopify
    image: shopify
    restart: unless-stopped
    volumes:
      - ./docker-server-config/production/php.ini:/etc/php/7.4/fpm/php.ini
      - ./docker-server-config/production/php.ini:/etc/php/7.4/cli/php.ini
      - ./docker-server-config/production/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-server-config/production/fpm-pool.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - ./docker-server-config/production/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./:/var/www/html
      - /var/www/html/vendor
      - ./docker-server-config/production/letsencrypt/:/etc/letsencrypt/
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    networks:
      - shopify-net
    environment:
      - PHP_MEM_LIMIT=2048M
      - PHP_POST_MAX_SIZE=1024M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - COMPOSER_MEMORY_LIMIT=-1
      - APP_NAME=Shopify

  shopify-mysql:
    image: mariadb:10.6.4
    container_name: shopify-mysql
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - shopify-net
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shopify
      MYSQL_USER: shopify
      MYSQL_PASSWORD: shopify

networks:
  shopify-net:
    driver: bridge
